module.exports = {
  appId: "app.bridge.desktop",
  productName: "Bridge",
  publish: [
    {
      provider: "generic",
      url: process.env.BRIDGE_UPDATE_BASE_URL || "https://api.customer.example/storage/v1/object/public/bridge-updates",
    },
  ],
  directories: {
    output: "release-bridge",
  },
  asar: true,
  asarUnpack: [
    "dist/bridge/bridge-voice/**",
  ],
  files: [
    "dist/bridge/**/*",
    "data-template/**/*",
    "public/**/*",
    "!public/bridge/**",
    "package.json",
    "node_modules/@anthropic-ai/**/*",
    "node_modules/openai/**/*",
    "node_modules/@supabase/**/*",
    "node_modules/electron-updater/**/*",
    "node_modules/builder-util-runtime/**/*",
    "node_modules/fs-extra/**/*",
    "node_modules/graceful-fs/**/*",
    "node_modules/jsonfile/**/*",
    "node_modules/lazy-val/**/*",
    "node_modules/lodash.isequal/**/*",
    "node_modules/semver/**/*",
    "node_modules/universalify/**/*",
    "node_modules/zod/**/*",
    "node_modules/yaml/**/*",
  ],
  extraMetadata: {
    main: "dist/bridge/electron-main.cjs",
  },
  protocols: [
    {
      name: "Bridge",
      schemes: ["bridge"],
    },
  ],
  mac: {
    category: "public.app-category.productivity",
    icon: "public/icon.icns",
    hardenedRuntime: true,
    gatekeeperAssess: false,
    entitlements: "build/entitlements.mac.plist",
    entitlementsInherit: "build/entitlements.mac.plist",
    target: ["dmg", "zip"],
  },
  win: {
    icon: "public/icon-512.png",
    target: ["nsis"],
    artifactName: "Bridge-Setup-${version}.exe",
  },
  nsis: {
    oneClick: true,
    perMachine: false,
    allowElevation: false,
    allowToChangeInstallationDirectory: false,
    deleteAppDataOnUninstall: false,
    guid: "app.bridge.desktop",
    include: "build/installer.nsh",
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    shortcutName: "Bridge",
    uninstallDisplayName: "Bridge",
    removeDefaultUninstallWelcomePage: true,
    runAfterFinish: true,
  },
};
